### ISSUE TITLE
Add links to a YouTube video and blog post

### ISSUE THREAD

**Issue by AlexGoOn** [sransara/speedscope-in-vscode#5]
First off, I want to thank you for creating such a useful extension. It's really helpful for debugging applications in VS Code.

I think it would be great to add a few links that demonstrate the extension in action. For example: 
YouTube: [Profile .NET MAUI Applications to Find Performance Issues](https://www.youtube.com/watch?v=-4VWRt_-PKw)
Blog post: [How to Profile .NET MAUI Applications and Isolate Performance-Related Issues](https://community.devexpress.com/blogs/mobile/archive/2024/04/01/How-to-Profile-NET-MAUI-Applications-and-Isolate-Performance-Related-Issues.aspx)

Both resources focus on profiling .NET MAUI apps and showcase the extension. I think this will make it easier for users to get started.

**Comment by sransara** [comment]
Thank you for sharing this. I'll add it in the README.
