### ISSUE TITLE
Automatic file detection

### ISSUE THREAD

**Issue by AndrewNolte** [sransara/speedscope-in-vscode#6]
I think it'd be nice for speedscope json files to automatically be opened, so the terminal link can just be clicked. There's a couple options here-
- Some standard format, like .spd.json, or .speedscope, etc.
- a hook for opening files, then checking if the json files starts with `{"$schema":"https://www.speedscope.app/file-format-schema.json"`

**Comment by sransara** [comment]
I tried adding a default file type from the extension itself but there seems to be some limitations: https://github.com/microsoft/vscode/issues/141562 (the workaround mentioned causes duplicate entries in the Opens With list)

I just found out you can specify custom editors in Workspace settings. So you can try something like this instead:

```
{
  "workbench.editorAssociations": {
      "*.speedscope.json": "speedscope-in-vscode.speedscope"
  }
}
```

> a hook for opening files, then checking if the json files starts with {"$schema":"https://www.speedscope.app/file-format-schema.json"

The extension will have to be activated first to do a magic number trick like this (if even possible). But my goal is to activate the extension only when absolutely necessary.

**Comment by AndrewNolte** [comment]
Cool thanks! That settings change works for me. I was trying files.associations before, which only applies to languages contributed, not editors. I think it'd be good to include instructions for that in the readme.
